version: '3.1'

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php:php
      - mysql:mysql
  php:
    build: docker/php
    restart: always
    volumes:
      - ./code:/var/www/html
    links:
      - mysql:mysql
  mysql:
    image: mysql:5.7.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/slow.log:/var/log/mysql-slow.log
      - ./mysql/dump:/dump
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
